-- Drop tables if they exist.  
-- create the tables with PKs first. 
-- Do DEPT_MANAGER last because it has FKs

DROP TABLE IF EXISTS DEPT_EMP cascade;
DROP TABLE IF EXISTS DEPARTMENTS cascade;
DROP TABLE IF EXISTS EMPLOYEES cascade;
DROP TABLE IF EXISTS SALARIES cascade;
DROP TABLE IF EXISTS TITLES cascade;
DROP TABLE IF EXISTS DEPT_MANAGER cascade;


-- Create the department table with the PK for dept_no

CREATE TABLE DEPARTMENTS(
	DEPT_NO char(10) NOT NULL,
	DEPT_NAME char(30) NOT NULL,
	PRIMARY KEY (DEPT_NO)
);


-- create employees table with emp_no as the PK

CREATE TABLE EMPLOYEES(
	EMP_NO char(10) NOT NULL,
	BIRTH_DATE char(10) NOT NULL,
	FIRST_NAME char(30),
	LAST_NAME char(30),
	GENDER char(1) NOT NULL,
	HIRE_DATE char(10) NOT NULL,
	PRIMARY KEY (EMP_NO)

);



-- create the salaries table with an FK that points to employees
CREATE TABLE SALARIES(
	EMP_NO char(10) NOT NULL,
	SALARY char(10) NOT NULL,
	FROM_DATE char(10) NOT NULL,
	TO_DATE char(10),
	CONSTRAINT EMP_SAL PRIMARY KEY (EMP_NO, FROM_DATE),
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO)

);


-- create titles with an FK also to employees

CREATE TABLE TITLES(
	EMP_NO char(10) NOT NULL,
	TITLE char(30),
	FROM_DATE char(10) NOT NULL,
	TO_DATE char(10),
	CONSTRAINT EMP_TITLE PRIMARY KEY (EMP_NO, FROM_DATE),
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO)

);


-- create the dept_manager table. FKs to employees and deparments. 

CREATE TABLE DEPT_MANAGER(
	DEPT_NO char(10) NOT NULL,
	EMP_NO char(10) NOT NULL,
	FROM_DATE char(10) NOT NULL,
	TO_DATE char(10) NOT NULL,
	CONSTRAINT MANAGER_PK PRIMARY KEY (DEPT_NO, EMP_NO, FROM_DATE),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO),
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO)

);


CREATE TABLE DEPT_EMP(
	EMP_NO char(10) NOT NULL,
	DEPT_NO char(10) NOT NULL,
	FROM_DATE char(10) NOT NULL,
	TO_DATE char(10) NOT NULL,
	CONSTRAINT DEPT_EMP_PK PRIMARY KEY (EMP_NO, DEPT_NO),
	FOREIGN KEY (EMP_NO) REFERENCES EMPLOYEES (EMP_NO) MATCH FULL,
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS (DEPT_NO) MATCH FULL
	
);


